<?php

namespace Blog\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    //добавлення кастомного метода
    public function getIdArrayByName($name){
        return $this->getEntityManager()
            ->createQuery("SELECT p.id FROM BlogBlogBundle:Post p WHERE p.title LIKE :name")
            ->setParameter('name','%'.$name.'%')
            ->getResult();
    }
}
